version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=isometips
    - POSTGRES_USER=isometips
    - POSTGRES_PASSWORD=esgi2018
    ports:
    - "5432:5432"
volumes:
  db-data: {}
